// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugin.proto

package resources

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JobExecutionRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Input                string   `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobExecutionRequest) Reset()         { *m = JobExecutionRequest{} }
func (m *JobExecutionRequest) String() string { return proto.CompactTextString(m) }
func (*JobExecutionRequest) ProtoMessage()    {}
func (*JobExecutionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{0}
}

func (m *JobExecutionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobExecutionRequest.Unmarshal(m, b)
}
func (m *JobExecutionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobExecutionRequest.Marshal(b, m, deterministic)
}
func (m *JobExecutionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobExecutionRequest.Merge(m, src)
}
func (m *JobExecutionRequest) XXX_Size() int {
	return xxx_messageInfo_JobExecutionRequest.Size(m)
}
func (m *JobExecutionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobExecutionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobExecutionRequest proto.InternalMessageInfo

func (m *JobExecutionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *JobExecutionRequest) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

type JobExecutionResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Output               string   `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobExecutionResponse) Reset()         { *m = JobExecutionResponse{} }
func (m *JobExecutionResponse) String() string { return proto.CompactTextString(m) }
func (*JobExecutionResponse) ProtoMessage()    {}
func (*JobExecutionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{1}
}

func (m *JobExecutionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobExecutionResponse.Unmarshal(m, b)
}
func (m *JobExecutionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobExecutionResponse.Marshal(b, m, deterministic)
}
func (m *JobExecutionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobExecutionResponse.Merge(m, src)
}
func (m *JobExecutionResponse) XXX_Size() int {
	return xxx_messageInfo_JobExecutionResponse.Size(m)
}
func (m *JobExecutionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobExecutionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobExecutionResponse proto.InternalMessageInfo

func (m *JobExecutionResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *JobExecutionResponse) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func init() {
	proto.RegisterType((*JobExecutionRequest)(nil), "resources.JobExecutionRequest")
	proto.RegisterType((*JobExecutionResponse)(nil), "resources.JobExecutionResponse")
}

func init() {
	proto.RegisterFile("plugin.proto", fileDescriptor_22a625af4bc1cc87)
}

var fileDescriptor_22a625af4bc1cc87 = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0xc8, 0x29, 0x4d,
	0xcf, 0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2c, 0x4a, 0x2d, 0xce, 0x2f, 0x2d,
	0x4a, 0x4e, 0x2d, 0x56, 0xb2, 0xe6, 0x12, 0xf6, 0xca, 0x4f, 0x72, 0xad, 0x48, 0x4d, 0x2e, 0x2d,
	0xc9, 0xcc, 0xcf, 0x0b, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0xe2, 0xe3, 0x62, 0xca, 0x4c,
	0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xca, 0x4c, 0x11, 0x12, 0xe1, 0x62, 0xcd, 0xcc,
	0x2b, 0x28, 0x2d, 0x91, 0x60, 0x02, 0x0b, 0x41, 0x38, 0x4a, 0x76, 0x5c, 0x22, 0xa8, 0x9a, 0x8b,
	0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x31, 0x74, 0x8b, 0x71, 0xb1, 0xe5, 0x97, 0x96, 0x20, 0xb4, 0x43,
	0x79, 0x46, 0x49, 0x5c, 0x6c, 0x01, 0x60, 0x77, 0x09, 0x45, 0x70, 0x09, 0x43, 0xad, 0x46, 0x36,
	0x50, 0x48, 0x4e, 0x0f, 0xee, 0x52, 0x3d, 0x2c, 0xce, 0x94, 0x92, 0xc7, 0x29, 0x0f, 0x71, 0x89,
	0x12, 0x43, 0x12, 0x1b, 0xd8, 0xcb, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x2d, 0xd5,
	0x06, 0x02, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PluginClient is the client API for Plugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PluginClient interface {
	RequestJobExecution(ctx context.Context, in *JobExecutionRequest, opts ...grpc.CallOption) (*JobExecutionResponse, error)
}

type pluginClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginClient(cc grpc.ClientConnInterface) PluginClient {
	return &pluginClient{cc}
}

func (c *pluginClient) RequestJobExecution(ctx context.Context, in *JobExecutionRequest, opts ...grpc.CallOption) (*JobExecutionResponse, error) {
	out := new(JobExecutionResponse)
	err := c.cc.Invoke(ctx, "/resources.Plugin/RequestJobExecution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServer is the server API for Plugin service.
type PluginServer interface {
	RequestJobExecution(context.Context, *JobExecutionRequest) (*JobExecutionResponse, error)
}

// UnimplementedPluginServer can be embedded to have forward compatible implementations.
type UnimplementedPluginServer struct {
}

func (*UnimplementedPluginServer) RequestJobExecution(ctx context.Context, req *JobExecutionRequest) (*JobExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestJobExecution not implemented")
}

func RegisterPluginServer(s *grpc.Server, srv PluginServer) {
	s.RegisterService(&_Plugin_serviceDesc, srv)
}

func _Plugin_RequestJobExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).RequestJobExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resources.Plugin/RequestJobExecution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).RequestJobExecution(ctx, req.(*JobExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Plugin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "resources.Plugin",
	HandlerType: (*PluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestJobExecution",
			Handler:    _Plugin_RequestJobExecution_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
