// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto.proto

package resources

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TaskExecutionRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Input                string   `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskExecutionRequest) Reset()         { *m = TaskExecutionRequest{} }
func (m *TaskExecutionRequest) String() string { return proto.CompactTextString(m) }
func (*TaskExecutionRequest) ProtoMessage()    {}
func (*TaskExecutionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{0}
}

func (m *TaskExecutionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskExecutionRequest.Unmarshal(m, b)
}
func (m *TaskExecutionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskExecutionRequest.Marshal(b, m, deterministic)
}
func (m *TaskExecutionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskExecutionRequest.Merge(m, src)
}
func (m *TaskExecutionRequest) XXX_Size() int {
	return xxx_messageInfo_TaskExecutionRequest.Size(m)
}
func (m *TaskExecutionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskExecutionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskExecutionRequest proto.InternalMessageInfo

func (m *TaskExecutionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TaskExecutionRequest) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

type TaskExecutionRequestResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Output               string   `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskExecutionRequestResponse) Reset()         { *m = TaskExecutionRequestResponse{} }
func (m *TaskExecutionRequestResponse) String() string { return proto.CompactTextString(m) }
func (*TaskExecutionRequestResponse) ProtoMessage()    {}
func (*TaskExecutionRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{1}
}

func (m *TaskExecutionRequestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskExecutionRequestResponse.Unmarshal(m, b)
}
func (m *TaskExecutionRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskExecutionRequestResponse.Marshal(b, m, deterministic)
}
func (m *TaskExecutionRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskExecutionRequestResponse.Merge(m, src)
}
func (m *TaskExecutionRequestResponse) XXX_Size() int {
	return xxx_messageInfo_TaskExecutionRequestResponse.Size(m)
}
func (m *TaskExecutionRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskExecutionRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskExecutionRequestResponse proto.InternalMessageInfo

func (m *TaskExecutionRequestResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TaskExecutionRequestResponse) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

type JobExecutionRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Input                string   `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobExecutionRequest) Reset()         { *m = JobExecutionRequest{} }
func (m *JobExecutionRequest) String() string { return proto.CompactTextString(m) }
func (*JobExecutionRequest) ProtoMessage()    {}
func (*JobExecutionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{2}
}

func (m *JobExecutionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobExecutionRequest.Unmarshal(m, b)
}
func (m *JobExecutionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobExecutionRequest.Marshal(b, m, deterministic)
}
func (m *JobExecutionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobExecutionRequest.Merge(m, src)
}
func (m *JobExecutionRequest) XXX_Size() int {
	return xxx_messageInfo_JobExecutionRequest.Size(m)
}
func (m *JobExecutionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobExecutionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobExecutionRequest proto.InternalMessageInfo

func (m *JobExecutionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *JobExecutionRequest) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

type JobExecutionRequestResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Output               string   `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobExecutionRequestResponse) Reset()         { *m = JobExecutionRequestResponse{} }
func (m *JobExecutionRequestResponse) String() string { return proto.CompactTextString(m) }
func (*JobExecutionRequestResponse) ProtoMessage()    {}
func (*JobExecutionRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{3}
}

func (m *JobExecutionRequestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobExecutionRequestResponse.Unmarshal(m, b)
}
func (m *JobExecutionRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobExecutionRequestResponse.Marshal(b, m, deterministic)
}
func (m *JobExecutionRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobExecutionRequestResponse.Merge(m, src)
}
func (m *JobExecutionRequestResponse) XXX_Size() int {
	return xxx_messageInfo_JobExecutionRequestResponse.Size(m)
}
func (m *JobExecutionRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobExecutionRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobExecutionRequestResponse proto.InternalMessageInfo

func (m *JobExecutionRequestResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *JobExecutionRequestResponse) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func init() {
	proto.RegisterType((*TaskExecutionRequest)(nil), "resources.TaskExecutionRequest")
	proto.RegisterType((*TaskExecutionRequestResponse)(nil), "resources.TaskExecutionRequestResponse")
	proto.RegisterType((*JobExecutionRequest)(nil), "resources.JobExecutionRequest")
	proto.RegisterType((*JobExecutionRequestResponse)(nil), "resources.JobExecutionRequestResponse")
}

func init() {
	proto.RegisterFile("proto.proto", fileDescriptor_2fcc84b9998d60d8)
}

var fileDescriptor_2fcc84b9998d60d8 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x03, 0x93, 0x42, 0x9c, 0x45, 0xa9, 0xc5, 0xf9, 0xa5, 0x45, 0xc9, 0xa9, 0xc5, 0x4a,
	0x36, 0x5c, 0x22, 0x21, 0x89, 0xc5, 0xd9, 0xae, 0x15, 0xa9, 0xc9, 0xa5, 0x25, 0x99, 0xf9, 0x79,
	0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0x9c, 0x41, 0x4c, 0x99, 0x29, 0x42, 0x22, 0x5c, 0xac, 0x99, 0x79, 0x05, 0xa5, 0x25,
	0x12, 0x4c, 0x60, 0x21, 0x08, 0x47, 0xc9, 0x8d, 0x4b, 0x06, 0x9b, 0xee, 0xa0, 0xd4, 0xe2, 0x82,
	0xfc, 0xbc, 0xe2, 0x54, 0x0c, 0x53, 0xc4, 0xb8, 0xd8, 0xf2, 0x4b, 0x4b, 0x10, 0xc6, 0x40, 0x79,
	0x4a, 0xd6, 0x5c, 0xc2, 0x5e, 0xf9, 0x49, 0x64, 0x3a, 0xc2, 0x95, 0x4b, 0x1a, 0x8b, 0x66, 0x52,
	0xdd, 0x60, 0x94, 0xc7, 0xc5, 0x11, 0x50, 0x94, 0x5f, 0x96, 0x99, 0x92, 0x5a, 0x24, 0x94, 0xc4,
	0x25, 0x02, 0x35, 0x06, 0xc5, 0x7b, 0x42, 0xf2, 0x7a, 0xf0, 0x90, 0xd3, 0xc3, 0xe6, 0x71, 0x29,
	0x75, 0x02, 0x0a, 0x60, 0xae, 0x52, 0x62, 0x30, 0xca, 0xe4, 0x62, 0x0b, 0xc8, 0x29, 0x4d, 0xcf,
	0xcc, 0x13, 0x8a, 0xe7, 0x12, 0x86, 0x4a, 0x23, 0xfb, 0x43, 0x48, 0x0e, 0xc9, 0x2c, 0x2c, 0x1e,
	0x94, 0x52, 0xc3, 0x2f, 0x8f, 0xb0, 0x2a, 0x89, 0x0d, 0x1c, 0xed, 0xc6, 0x80, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x5c, 0xf2, 0x43, 0x1d, 0x05, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProviderClient is the client API for Provider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProviderClient interface {
	RequestTaskExecution(ctx context.Context, in *TaskExecutionRequest, opts ...grpc.CallOption) (*TaskExecutionRequestResponse, error)
}

type providerClient struct {
	cc grpc.ClientConnInterface
}

func NewProviderClient(cc grpc.ClientConnInterface) ProviderClient {
	return &providerClient{cc}
}

func (c *providerClient) RequestTaskExecution(ctx context.Context, in *TaskExecutionRequest, opts ...grpc.CallOption) (*TaskExecutionRequestResponse, error) {
	out := new(TaskExecutionRequestResponse)
	err := c.cc.Invoke(ctx, "/resources.Provider/RequestTaskExecution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProviderServer is the server API for Provider service.
type ProviderServer interface {
	RequestTaskExecution(context.Context, *TaskExecutionRequest) (*TaskExecutionRequestResponse, error)
}

// UnimplementedProviderServer can be embedded to have forward compatible implementations.
type UnimplementedProviderServer struct {
}

func (*UnimplementedProviderServer) RequestTaskExecution(ctx context.Context, req *TaskExecutionRequest) (*TaskExecutionRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestTaskExecution not implemented")
}

func RegisterProviderServer(s *grpc.Server, srv ProviderServer) {
	s.RegisterService(&_Provider_serviceDesc, srv)
}

func _Provider_RequestTaskExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).RequestTaskExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resources.Provider/RequestTaskExecution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).RequestTaskExecution(ctx, req.(*TaskExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Provider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "resources.Provider",
	HandlerType: (*ProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestTaskExecution",
			Handler:    _Provider_RequestTaskExecution_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}

// PluginClient is the client API for Plugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PluginClient interface {
	RequestJobExecution(ctx context.Context, in *JobExecutionRequest, opts ...grpc.CallOption) (*JobExecutionRequestResponse, error)
}

type pluginClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginClient(cc grpc.ClientConnInterface) PluginClient {
	return &pluginClient{cc}
}

func (c *pluginClient) RequestJobExecution(ctx context.Context, in *JobExecutionRequest, opts ...grpc.CallOption) (*JobExecutionRequestResponse, error) {
	out := new(JobExecutionRequestResponse)
	err := c.cc.Invoke(ctx, "/resources.Plugin/RequestJobExecution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServer is the server API for Plugin service.
type PluginServer interface {
	RequestJobExecution(context.Context, *JobExecutionRequest) (*JobExecutionRequestResponse, error)
}

// UnimplementedPluginServer can be embedded to have forward compatible implementations.
type UnimplementedPluginServer struct {
}

func (*UnimplementedPluginServer) RequestJobExecution(ctx context.Context, req *JobExecutionRequest) (*JobExecutionRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestJobExecution not implemented")
}

func RegisterPluginServer(s *grpc.Server, srv PluginServer) {
	s.RegisterService(&_Plugin_serviceDesc, srv)
}

func _Plugin_RequestJobExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).RequestJobExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resources.Plugin/RequestJobExecution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).RequestJobExecution(ctx, req.(*JobExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Plugin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "resources.Plugin",
	HandlerType: (*PluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestJobExecution",
			Handler:    _Plugin_RequestJobExecution_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}
