// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto.proto

package resources

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TaskExecutionRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Input                string   `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskExecutionRequest) Reset()         { *m = TaskExecutionRequest{} }
func (m *TaskExecutionRequest) String() string { return proto.CompactTextString(m) }
func (*TaskExecutionRequest) ProtoMessage()    {}
func (*TaskExecutionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{0}
}

func (m *TaskExecutionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskExecutionRequest.Unmarshal(m, b)
}
func (m *TaskExecutionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskExecutionRequest.Marshal(b, m, deterministic)
}
func (m *TaskExecutionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskExecutionRequest.Merge(m, src)
}
func (m *TaskExecutionRequest) XXX_Size() int {
	return xxx_messageInfo_TaskExecutionRequest.Size(m)
}
func (m *TaskExecutionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskExecutionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskExecutionRequest proto.InternalMessageInfo

func (m *TaskExecutionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TaskExecutionRequest) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

type TaskExecutionRequestResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskExecutionRequestResponse) Reset()         { *m = TaskExecutionRequestResponse{} }
func (m *TaskExecutionRequestResponse) String() string { return proto.CompactTextString(m) }
func (*TaskExecutionRequestResponse) ProtoMessage()    {}
func (*TaskExecutionRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{1}
}

func (m *TaskExecutionRequestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskExecutionRequestResponse.Unmarshal(m, b)
}
func (m *TaskExecutionRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskExecutionRequestResponse.Marshal(b, m, deterministic)
}
func (m *TaskExecutionRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskExecutionRequestResponse.Merge(m, src)
}
func (m *TaskExecutionRequestResponse) XXX_Size() int {
	return xxx_messageInfo_TaskExecutionRequestResponse.Size(m)
}
func (m *TaskExecutionRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskExecutionRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskExecutionRequestResponse proto.InternalMessageInfo

func (m *TaskExecutionRequestResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type TaskAcceptanceRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Output               string   `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskAcceptanceRequest) Reset()         { *m = TaskAcceptanceRequest{} }
func (m *TaskAcceptanceRequest) String() string { return proto.CompactTextString(m) }
func (*TaskAcceptanceRequest) ProtoMessage()    {}
func (*TaskAcceptanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{2}
}

func (m *TaskAcceptanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskAcceptanceRequest.Unmarshal(m, b)
}
func (m *TaskAcceptanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskAcceptanceRequest.Marshal(b, m, deterministic)
}
func (m *TaskAcceptanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskAcceptanceRequest.Merge(m, src)
}
func (m *TaskAcceptanceRequest) XXX_Size() int {
	return xxx_messageInfo_TaskAcceptanceRequest.Size(m)
}
func (m *TaskAcceptanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskAcceptanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskAcceptanceRequest proto.InternalMessageInfo

func (m *TaskAcceptanceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TaskAcceptanceRequest) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

type TaskAcceptanceRequestResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskAcceptanceRequestResponse) Reset()         { *m = TaskAcceptanceRequestResponse{} }
func (m *TaskAcceptanceRequestResponse) String() string { return proto.CompactTextString(m) }
func (*TaskAcceptanceRequestResponse) ProtoMessage()    {}
func (*TaskAcceptanceRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{3}
}

func (m *TaskAcceptanceRequestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskAcceptanceRequestResponse.Unmarshal(m, b)
}
func (m *TaskAcceptanceRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskAcceptanceRequestResponse.Marshal(b, m, deterministic)
}
func (m *TaskAcceptanceRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskAcceptanceRequestResponse.Merge(m, src)
}
func (m *TaskAcceptanceRequestResponse) XXX_Size() int {
	return xxx_messageInfo_TaskAcceptanceRequestResponse.Size(m)
}
func (m *TaskAcceptanceRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskAcceptanceRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskAcceptanceRequestResponse proto.InternalMessageInfo

func (m *TaskAcceptanceRequestResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*TaskExecutionRequest)(nil), "resources.TaskExecutionRequest")
	proto.RegisterType((*TaskExecutionRequestResponse)(nil), "resources.TaskExecutionRequestResponse")
	proto.RegisterType((*TaskAcceptanceRequest)(nil), "resources.TaskAcceptanceRequest")
	proto.RegisterType((*TaskAcceptanceRequestResponse)(nil), "resources.TaskAcceptanceRequestResponse")
}

func init() {
	proto.RegisterFile("proto.proto", fileDescriptor_2fcc84b9998d60d8)
}

var fileDescriptor_2fcc84b9998d60d8 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x03, 0x93, 0x42, 0x9c, 0x45, 0xa9, 0xc5, 0xf9, 0xa5, 0x45, 0xc9, 0xa9, 0xc5, 0x4a,
	0x36, 0x5c, 0x22, 0x21, 0x89, 0xc5, 0xd9, 0xae, 0x15, 0xa9, 0xc9, 0xa5, 0x25, 0x99, 0xf9, 0x79,
	0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0x9c, 0x41, 0x4c, 0x99, 0x29, 0x42, 0x22, 0x5c, 0xac, 0x99, 0x79, 0x05, 0xa5, 0x25,
	0x12, 0x4c, 0x60, 0x21, 0x08, 0x47, 0x49, 0x8f, 0x4b, 0x06, 0x9b, 0xee, 0xa0, 0xd4, 0xe2, 0x82,
	0xfc, 0xbc, 0xe2, 0x54, 0x74, 0x53, 0x94, 0xec, 0xb9, 0x44, 0x41, 0xea, 0x1d, 0x93, 0x93, 0x53,
	0x0b, 0x4a, 0x12, 0xf3, 0x92, 0x53, 0x71, 0x59, 0x27, 0xc6, 0xc5, 0x96, 0x5f, 0x5a, 0x82, 0xb0,
	0x0f, 0xca, 0x53, 0xd2, 0xe7, 0x92, 0xc5, 0x6a, 0x00, 0x2e, 0x1b, 0x8d, 0xf2, 0xb8, 0x38, 0x02,
	0x8a, 0xf2, 0xcb, 0x32, 0x53, 0x52, 0x8b, 0x84, 0x92, 0xb8, 0x44, 0xa0, 0xca, 0x51, 0x1c, 0x2d,
	0x24, 0xaf, 0x07, 0x0f, 0x0f, 0x3d, 0x6c, 0xde, 0x91, 0x52, 0x27, 0xa0, 0x00, 0x66, 0xbb, 0x12,
	0x83, 0x51, 0x11, 0x17, 0x27, 0x54, 0x30, 0xb5, 0x48, 0x28, 0x95, 0x4b, 0x14, 0xc9, 0x42, 0x84,
	0xa3, 0x85, 0x14, 0xd0, 0x0c, 0xc4, 0xf0, 0x8f, 0x94, 0x06, 0x21, 0x15, 0x08, 0x3b, 0x93, 0xd8,
	0xc0, 0xb1, 0x6a, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x6f, 0x59, 0x24, 0xe4, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProviderClient is the client API for Provider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProviderClient interface {
	RequestTaskExecution(ctx context.Context, in *TaskExecutionRequest, opts ...grpc.CallOption) (*TaskExecutionRequestResponse, error)
}

type providerClient struct {
	cc grpc.ClientConnInterface
}

func NewProviderClient(cc grpc.ClientConnInterface) ProviderClient {
	return &providerClient{cc}
}

func (c *providerClient) RequestTaskExecution(ctx context.Context, in *TaskExecutionRequest, opts ...grpc.CallOption) (*TaskExecutionRequestResponse, error) {
	out := new(TaskExecutionRequestResponse)
	err := c.cc.Invoke(ctx, "/resources.Provider/RequestTaskExecution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProviderServer is the server API for Provider service.
type ProviderServer interface {
	RequestTaskExecution(context.Context, *TaskExecutionRequest) (*TaskExecutionRequestResponse, error)
}

// UnimplementedProviderServer can be embedded to have forward compatible implementations.
type UnimplementedProviderServer struct {
}

func (*UnimplementedProviderServer) RequestTaskExecution(ctx context.Context, req *TaskExecutionRequest) (*TaskExecutionRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestTaskExecution not implemented")
}

func RegisterProviderServer(s *grpc.Server, srv ProviderServer) {
	s.RegisterService(&_Provider_serviceDesc, srv)
}

func _Provider_RequestTaskExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).RequestTaskExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resources.Provider/RequestTaskExecution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).RequestTaskExecution(ctx, req.(*TaskExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Provider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "resources.Provider",
	HandlerType: (*ProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestTaskExecution",
			Handler:    _Provider_RequestTaskExecution_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}

// RequesterClient is the client API for Requester service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RequesterClient interface {
	RequestTaskAcceptance(ctx context.Context, in *TaskAcceptanceRequest, opts ...grpc.CallOption) (*TaskAcceptanceRequestResponse, error)
}

type requesterClient struct {
	cc grpc.ClientConnInterface
}

func NewRequesterClient(cc grpc.ClientConnInterface) RequesterClient {
	return &requesterClient{cc}
}

func (c *requesterClient) RequestTaskAcceptance(ctx context.Context, in *TaskAcceptanceRequest, opts ...grpc.CallOption) (*TaskAcceptanceRequestResponse, error) {
	out := new(TaskAcceptanceRequestResponse)
	err := c.cc.Invoke(ctx, "/resources.Requester/RequestTaskAcceptance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RequesterServer is the server API for Requester service.
type RequesterServer interface {
	RequestTaskAcceptance(context.Context, *TaskAcceptanceRequest) (*TaskAcceptanceRequestResponse, error)
}

// UnimplementedRequesterServer can be embedded to have forward compatible implementations.
type UnimplementedRequesterServer struct {
}

func (*UnimplementedRequesterServer) RequestTaskAcceptance(ctx context.Context, req *TaskAcceptanceRequest) (*TaskAcceptanceRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestTaskAcceptance not implemented")
}

func RegisterRequesterServer(s *grpc.Server, srv RequesterServer) {
	s.RegisterService(&_Requester_serviceDesc, srv)
}

func _Requester_RequestTaskAcceptance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskAcceptanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequesterServer).RequestTaskAcceptance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resources.Requester/RequestTaskAcceptance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequesterServer).RequestTaskAcceptance(ctx, req.(*TaskAcceptanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Requester_serviceDesc = grpc.ServiceDesc{
	ServiceName: "resources.Requester",
	HandlerType: (*RequesterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestTaskAcceptance",
			Handler:    _Requester_RequestTaskAcceptance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}
