// Code generated by protoc-gen-go. DO NOT EDIT.
// source: provider.proto

package resources

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TaskExecutionRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Input                string   `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskExecutionRequest) Reset()         { *m = TaskExecutionRequest{} }
func (m *TaskExecutionRequest) String() string { return proto.CompactTextString(m) }
func (*TaskExecutionRequest) ProtoMessage()    {}
func (*TaskExecutionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a9f3c02af3d1c8, []int{0}
}

func (m *TaskExecutionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskExecutionRequest.Unmarshal(m, b)
}
func (m *TaskExecutionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskExecutionRequest.Marshal(b, m, deterministic)
}
func (m *TaskExecutionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskExecutionRequest.Merge(m, src)
}
func (m *TaskExecutionRequest) XXX_Size() int {
	return xxx_messageInfo_TaskExecutionRequest.Size(m)
}
func (m *TaskExecutionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskExecutionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskExecutionRequest proto.InternalMessageInfo

func (m *TaskExecutionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TaskExecutionRequest) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

type TaskExecutionResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Output               string   `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskExecutionResponse) Reset()         { *m = TaskExecutionResponse{} }
func (m *TaskExecutionResponse) String() string { return proto.CompactTextString(m) }
func (*TaskExecutionResponse) ProtoMessage()    {}
func (*TaskExecutionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a9f3c02af3d1c8, []int{1}
}

func (m *TaskExecutionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskExecutionResponse.Unmarshal(m, b)
}
func (m *TaskExecutionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskExecutionResponse.Marshal(b, m, deterministic)
}
func (m *TaskExecutionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskExecutionResponse.Merge(m, src)
}
func (m *TaskExecutionResponse) XXX_Size() int {
	return xxx_messageInfo_TaskExecutionResponse.Size(m)
}
func (m *TaskExecutionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskExecutionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskExecutionResponse proto.InternalMessageInfo

func (m *TaskExecutionResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TaskExecutionResponse) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func init() {
	proto.RegisterType((*TaskExecutionRequest)(nil), "resources.TaskExecutionRequest")
	proto.RegisterType((*TaskExecutionResponse)(nil), "resources.TaskExecutionResponse")
}

func init() {
	proto.RegisterFile("provider.proto", fileDescriptor_c6a9f3c02af3d1c8)
}

var fileDescriptor_c6a9f3c02af3d1c8 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x28, 0xca, 0x2f,
	0xcb, 0x4c, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2c, 0x4a, 0x2d, 0xce,
	0x2f, 0x2d, 0x4a, 0x4e, 0x2d, 0x56, 0xb2, 0xe1, 0x12, 0x09, 0x49, 0x2c, 0xce, 0x76, 0xad, 0x48,
	0x4d, 0x2e, 0x2d, 0xc9, 0xcc, 0xcf, 0x0b, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0xe2, 0xe3,
	0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xca, 0x4c, 0x11, 0x12, 0xe1,
	0x62, 0xcd, 0xcc, 0x2b, 0x28, 0x2d, 0x91, 0x60, 0x02, 0x0b, 0x41, 0x38, 0x4a, 0xf6, 0x5c, 0xa2,
	0x68, 0xba, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x31, 0xb4, 0x8b, 0x71, 0xb1, 0xe5, 0x97, 0x96,
	0x20, 0xf4, 0x43, 0x79, 0x46, 0xe9, 0x5c, 0x1c, 0x01, 0x50, 0xb7, 0x09, 0x45, 0x73, 0x89, 0x40,
	0x6d, 0x47, 0x31, 0x53, 0x48, 0x5e, 0x0f, 0xee, 0x5c, 0x3d, 0x6c, 0x6e, 0x95, 0x52, 0xc0, 0xad,
	0x00, 0xe2, 0x1c, 0x25, 0x86, 0x24, 0x36, 0xb0, 0xcf, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xcc, 0x1d, 0xd6, 0xc0, 0x0b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProviderClient is the client API for Provider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProviderClient interface {
	RequestTaskExecution(ctx context.Context, in *TaskExecutionRequest, opts ...grpc.CallOption) (*TaskExecutionResponse, error)
}

type providerClient struct {
	cc grpc.ClientConnInterface
}

func NewProviderClient(cc grpc.ClientConnInterface) ProviderClient {
	return &providerClient{cc}
}

func (c *providerClient) RequestTaskExecution(ctx context.Context, in *TaskExecutionRequest, opts ...grpc.CallOption) (*TaskExecutionResponse, error) {
	out := new(TaskExecutionResponse)
	err := c.cc.Invoke(ctx, "/resources.Provider/RequestTaskExecution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProviderServer is the server API for Provider service.
type ProviderServer interface {
	RequestTaskExecution(context.Context, *TaskExecutionRequest) (*TaskExecutionResponse, error)
}

// UnimplementedProviderServer can be embedded to have forward compatible implementations.
type UnimplementedProviderServer struct {
}

func (*UnimplementedProviderServer) RequestTaskExecution(ctx context.Context, req *TaskExecutionRequest) (*TaskExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestTaskExecution not implemented")
}

func RegisterProviderServer(s *grpc.Server, srv ProviderServer) {
	s.RegisterService(&_Provider_serviceDesc, srv)
}

func _Provider_RequestTaskExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).RequestTaskExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resources.Provider/RequestTaskExecution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).RequestTaskExecution(ctx, req.(*TaskExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Provider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "resources.Provider",
	HandlerType: (*ProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestTaskExecution",
			Handler:    _Provider_RequestTaskExecution_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "provider.proto",
}
